# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'remotecontrol.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(440, 575)
        MainWindow.setMinimumSize(QtCore.QSize(440, 575))
        MainWindow.setMaximumSize(QtCore.QSize(440, 575))
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_screen = QtWidgets.QLabel(self.centralwidget)
        self.label_screen.setMinimumSize(QtCore.QSize(400, 300))
        self.label_screen.setMaximumSize(QtCore.QSize(400, 300))
        self.label_screen.setFrameShape(QtWidgets.QFrame.Box)
        self.label_screen.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_screen.setLineWidth(2)
        self.label_screen.setMidLineWidth(2)
        self.label_screen.setText("")
        self.label_screen.setPixmap(QtGui.QPixmap("images/blackstatic.jpg"))
        self.label_screen.setScaledContents(True)
        self.label_screen.setAlignment(QtCore.Qt.AlignCenter)
        self.label_screen.setObjectName("label_screen")
        self.verticalLayout_2.addWidget(self.label_screen, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_channeldisplay = QtWidgets.QLabel(self.centralwidget)
        self.label_channeldisplay.setMinimumSize(QtCore.QSize(50, 40))
        self.label_channeldisplay.setMaximumSize(QtCore.QSize(50, 40))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(32)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_channeldisplay.setFont(font)
        self.label_channeldisplay.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_channeldisplay.setObjectName("label_channeldisplay")
        self.horizontalLayout.addWidget(self.label_channeldisplay)
        self.lcd_channel = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcd_channel.setMinimumSize(QtCore.QSize(75, 40))
        self.lcd_channel.setMaximumSize(QtCore.QSize(75, 40))
        self.lcd_channel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lcd_channel.setDigitCount(3)
        self.lcd_channel.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcd_channel.setObjectName("lcd_channel")
        self.horizontalLayout.addWidget(self.lcd_channel)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.label_volumedisplay = QtWidgets.QLabel(self.centralwidget)
        self.label_volumedisplay.setMinimumSize(QtCore.QSize(50, 40))
        self.label_volumedisplay.setMaximumSize(QtCore.QSize(50, 40))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(32)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_volumedisplay.setFont(font)
        self.label_volumedisplay.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_volumedisplay.setObjectName("label_volumedisplay")
        self.horizontalLayout.addWidget(self.label_volumedisplay, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignVCenter)
        self.lcd_volume = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcd_volume.setMinimumSize(QtCore.QSize(75, 40))
        self.lcd_volume.setMaximumSize(QtCore.QSize(75, 40))
        self.lcd_volume.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lcd_volume.setSmallDecimalPoint(False)
        self.lcd_volume.setDigitCount(3)
        self.lcd_volume.setMode(QtWidgets.QLCDNumber.Dec)
        self.lcd_volume.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcd_volume.setProperty("value", 0.0)
        self.lcd_volume.setProperty("intValue", 0)
        self.lcd_volume.setObjectName("lcd_volume")
        self.horizontalLayout.addWidget(self.lcd_volume, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.line = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setMinimumSize(QtCore.QSize(400, 0))
        self.line.setMaximumSize(QtCore.QSize(400, 16777215))
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line, 0, QtCore.Qt.AlignHCenter)
        self.label_channelbuttons = QtWidgets.QLabel(self.centralwidget)
        self.label_channelbuttons.setMinimumSize(QtCore.QSize(50, 30))
        self.label_channelbuttons.setMaximumSize(QtCore.QSize(50, 30))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.label_channelbuttons.setFont(font)
        self.label_channelbuttons.setAlignment(QtCore.Qt.AlignCenter)
        self.label_channelbuttons.setObjectName("label_channelbuttons")
        self.verticalLayout_2.addWidget(self.label_channelbuttons, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.pushButton_chdown = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_chdown.sizePolicy().hasHeightForWidth())
        self.pushButton_chdown.setSizePolicy(sizePolicy)
        self.pushButton_chdown.setMinimumSize(QtCore.QSize(80, 40))
        self.pushButton_chdown.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton_chdown.setStyleSheet("QPushButton {\n"
"    border: 2px solid #000000;\n"
"    border-radius: 20px;\n"
"    background-color:#D5D5D5;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #C5C5C5;\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #B5B5B5 ;\n"
"    }")
        self.pushButton_chdown.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/rewind.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_chdown.setIcon(icon)
        self.pushButton_chdown.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_chdown.setObjectName("pushButton_chdown")
        self.horizontalLayout_3.addWidget(self.pushButton_chdown, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignTop)
        self.pushButton_power = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_power.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_power.sizePolicy().hasHeightForWidth())
        self.pushButton_power.setSizePolicy(sizePolicy)
        self.pushButton_power.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_power.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton_power.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_power.setStyleSheet("QPushButton {\n"
"    border: 2px solid #000000;\n"
"    border-radius: 20px;\n"
"    background-color:#D5D5D5;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #C5C5C5;\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #B5B5B5 ;\n"
"    }")
        self.pushButton_power.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/power.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_power.setIcon(icon1)
        self.pushButton_power.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_power.setDefault(False)
        self.pushButton_power.setFlat(False)
        self.pushButton_power.setObjectName("pushButton_power")
        self.horizontalLayout_3.addWidget(self.pushButton_power, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.pushButton_chup = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_chup.sizePolicy().hasHeightForWidth())
        self.pushButton_chup.setSizePolicy(sizePolicy)
        self.pushButton_chup.setMinimumSize(QtCore.QSize(80, 40))
        self.pushButton_chup.setMaximumSize(QtCore.QSize(80, 40))
        self.pushButton_chup.setStyleSheet("QPushButton {\n"
"    border: 2px solid #000000;\n"
"    border-radius: 20px;\n"
"    background-color:#D5D5D5;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #C5C5C5;\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #B5B5B5 ;\n"
"    }")
        self.pushButton_chup.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("images/fastfoward.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_chup.setIcon(icon2)
        self.pushButton_chup.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_chup.setObjectName("pushButton_chup")
        self.horizontalLayout_3.addWidget(self.pushButton_chup, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.label_volumebuttons = QtWidgets.QLabel(self.centralwidget)
        self.label_volumebuttons.setMinimumSize(QtCore.QSize(50, 30))
        self.label_volumebuttons.setMaximumSize(QtCore.QSize(50, 30))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)
        font.setUnderline(True)
        self.label_volumebuttons.setFont(font)
        self.label_volumebuttons.setAlignment(QtCore.Qt.AlignCenter)
        self.label_volumebuttons.setObjectName("label_volumebuttons")
        self.verticalLayout.addWidget(self.label_volumebuttons, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.pushButton_mute = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_mute.sizePolicy().hasHeightForWidth())
        self.pushButton_mute.setSizePolicy(sizePolicy)
        self.pushButton_mute.setMinimumSize(QtCore.QSize(80, 40))
        self.pushButton_mute.setMaximumSize(QtCore.QSize(80, 40))
        self.pushButton_mute.setStyleSheet("QPushButton {\n"
"    border: 2px solid #000000;\n"
"    border-radius: 20px;\n"
"    background-color:#D5D5D5;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #C5C5C5;\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #B5B5B5 ;\n"
"    }")
        self.pushButton_mute.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("images/mute.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_mute.setIcon(icon3)
        self.pushButton_mute.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_mute.setObjectName("pushButton_mute")
        self.horizontalLayout_4.addWidget(self.pushButton_mute, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignTop)
        self.pushButton_voldown = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_voldown.sizePolicy().hasHeightForWidth())
        self.pushButton_voldown.setSizePolicy(sizePolicy)
        self.pushButton_voldown.setMinimumSize(QtCore.QSize(80, 40))
        self.pushButton_voldown.setMaximumSize(QtCore.QSize(80, 40))
        self.pushButton_voldown.setStyleSheet("QPushButton {\n"
"    border: 2px solid #000000;\n"
"    border-radius: 20px;\n"
"    background-color:#D5D5D5;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #C5C5C5;\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #B5B5B5 ;\n"
"    }")
        self.pushButton_voldown.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("images/voldown.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_voldown.setIcon(icon4)
        self.pushButton_voldown.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_voldown.setObjectName("pushButton_voldown")
        self.horizontalLayout_4.addWidget(self.pushButton_voldown, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.pushButton_volup = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_volup.sizePolicy().hasHeightForWidth())
        self.pushButton_volup.setSizePolicy(sizePolicy)
        self.pushButton_volup.setMinimumSize(QtCore.QSize(80, 40))
        self.pushButton_volup.setMaximumSize(QtCore.QSize(80, 40))
        self.pushButton_volup.setStyleSheet("QPushButton {\n"
"    border: 2px solid #000000;\n"
"    border-radius: 20px;\n"
"    background-color:#D5D5D5;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #C5C5C5;\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #B5B5B5 ;\n"
"    }")
        self.pushButton_volup.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("images/volup.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_volup.setIcon(icon5)
        self.pushButton_volup.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_volup.setObjectName("pushButton_volup")
        self.horizontalLayout_4.addWidget(self.pushButton_volup, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        spacerItem7 = QtWidgets.QSpacerItem(20, 1, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem7)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Controller"))
        self.label_channeldisplay.setText(_translate("MainWindow", "CH"))
        self.label_volumedisplay.setText(_translate("MainWindow", "VOL"))
        self.label_channelbuttons.setText(_translate("MainWindow", "Channel"))
        self.label_volumebuttons.setText(_translate("MainWindow", "Volume"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
